package me.FurH.CreativeControl.configuration;

import org.bukkit.*;
import java.util.*;
import me.FurH.CreativeControl.stack.*;

public class CreativeWorldNodes
{
    public GameMode world_gamemode;
    public boolean world_exclude;
    public boolean world_changegm;
    public HashSet<String> black_cmds;
    public HashSet<String> black_s_cmds;
    public HashSet<CreativeItemStack> black_place;
    public HashSet<CreativeItemStack> black_break;
    public HashSet<CreativeItemStack> black_use;
    public HashSet<CreativeItemStack> black_interact;
    public HashSet<CreativeItemStack> black_inventory;
    public HashSet<String> black_sign;
    public boolean black_sign_all;
    public boolean misc_tnt;
    public boolean misc_ice;
    public boolean misc_liquid;
    public boolean misc_fire;
    public boolean block_water;
    public boolean block_worledit;
    public boolean block_ownblock;
    public boolean block_nodrop;
    public boolean block_explosion;
    public boolean block_creative;
    public boolean block_pistons;
    public boolean block_physics;
    public boolean block_against;
    public boolean block_attach;
    public boolean block_invert;
    public HashSet<CreativeItemStack> block_exclude;
    public int block_minutelimit;
    public boolean prevent_drop;
    public boolean prevent_pickup;
    public boolean prevent_pvp;
    public boolean prevent_mobs;
    public boolean prevent_eggs;
    public boolean prevent_target;
    public boolean prevent_mobsdrop;
    public boolean prevent_irongolem;
    public boolean prevent_snowgolem;
    public boolean prevent_wither;
    public boolean prevent_drops;
    public boolean prevent_enchant;
    public boolean prevent_mcstore;
    public boolean prevent_bedrock;
    public boolean prevent_invinteract;
    public boolean prevent_bonemeal;
    public boolean prevent_villager;
    public boolean prevent_potion;
    public boolean prevent_frame;
    public boolean prevent_vehicle;
    public int prevent_limitvechile;
    public int prevent_stacklimit;
    public boolean prevent_open;
    public boolean prevent_fly;
    public boolean prevent_creative;
    
    public CreativeWorldNodes() {
        super();
        this.world_gamemode = GameMode.SURVIVAL;
        this.world_exclude = false;
        this.world_changegm = false;
        this.black_cmds = new HashSet<String>();
        this.black_s_cmds = new HashSet<String>();
        this.black_place = new HashSet<CreativeItemStack>();
        this.black_break = new HashSet<CreativeItemStack>();
        this.black_use = new HashSet<CreativeItemStack>();
        this.black_interact = new HashSet<CreativeItemStack>();
        this.black_inventory = new HashSet<CreativeItemStack>();
        this.black_sign = new HashSet<String>();
        this.black_sign_all = false;
        this.misc_tnt = false;
        this.misc_ice = false;
        this.misc_liquid = false;
        this.misc_fire = false;
        this.block_water = false;
        this.block_worledit = false;
        this.block_ownblock = false;
        this.block_nodrop = true;
        this.block_explosion = false;
        this.block_creative = false;
        this.block_pistons = false;
        this.block_physics = false;
        this.block_against = false;
        this.block_attach = false;
        this.block_invert = false;
        this.block_exclude = new HashSet<CreativeItemStack>();
        this.block_minutelimit = -1;
        this.prevent_drop = true;
        this.prevent_pickup = true;
        this.prevent_pvp = true;
        this.prevent_mobs = false;
        this.prevent_eggs = true;
        this.prevent_target = false;
        this.prevent_mobsdrop = true;
        this.prevent_irongolem = true;
        this.prevent_snowgolem = true;
        this.prevent_wither = true;
        this.prevent_drops = true;
        this.prevent_enchant = true;
        this.prevent_mcstore = true;
        this.prevent_bedrock = true;
        this.prevent_invinteract = true;
        this.prevent_bonemeal = true;
        this.prevent_villager = true;
        this.prevent_potion = true;
        this.prevent_frame = true;
        this.prevent_vehicle = true;
        this.prevent_limitvechile = -1;
        this.prevent_stacklimit = 1;
        this.prevent_open = false;
        this.prevent_fly = false;
        this.prevent_creative = false;
    }
}
